<?php

declare(strict_types=1);

namespace OCA\Reel\Service;

use OCA\Reel\AppInfo\Application;
use OCP\Files\File;
use OCP\Files\Folder;
use OCP\Files\IRootFolder;
use OCP\IConfig;
use OCP\IDBConnection;
use OCP\DB\QueryBuilder\IQueryBuilder;
use Psr\Log\LoggerInterface;

/**
 * VideoRenderingService
 *
 * Renders a highlight video for a Reel event using FFmpeg.
 *
 * Strategy — two-pass rendering:
 *   Pass 1: Normalize every input (photo or video, any codec) to a
 *           temporary 1080p H.264 30fps intermediate clip.
 *   Pass 2: Concatenate all intermediates and encode the final H.265 MP4.
 *
 * This approach handles any input codec/container reliably.
 */
class VideoRenderingService {

    // How long each photo is shown (seconds)
    private const PHOTO_DURATION = 2.5;

    // Maximum duration of a video clip (seconds)
    private const MAX_CLIP_DURATION = 8.0;

    // Output dimensions
    private const WIDTH  = 1920;
    private const HEIGHT = 1080;

    // Frames per second for all intermediates and output
    private const FPS = 30;

    // Where to save generated videos in the user's file tree
    private const OUTPUT_FOLDER = 'Reels';

    private const FFMPEG_TIMEOUT_SECONDS = 1800;
    private const FFMPEG_STDERR_MAX_BYTES = 262144;
    private const TARGET_ASPECT = self::WIDTH / self::HEIGHT;
    private const MUSIC_BASE_VOLUME = 0.50;
    private const MUSIC_DUCKED_VOLUME = 1.00;
    private const MUSIC_FADE_OUT_SECONDS = 2.4;
    private const AUDIO_CROSSFADE_SECONDS = 0.10;
    private const INTRO_TEXT_DURATION_SECONDS = 2.5;
    private const OUTRO_VIDEO_FADE_SECONDS = 3.0;

    private int $outputWidth = self::WIDTH;
    private int $outputHeight = self::HEIGHT;

    public function __construct(
        private IDBConnection   $db,
        private IRootFolder     $rootFolder,
        private LoggerInterface $logger,
        private IConfig         $config,
        private MemoriesRepository $memoriesRepository,
        private MusicService $musicService,
    ) {}

    /**
     * Render a video for the given event ID.
     * Returns the Nextcloud file ID of the generated video.
     */
    public function renderEvent(int $eventId, string $userId, ?callable $onProgress = null, ?callable $onDebug = null): int {
        $this->logger->info('Reel: starting render for event {id}', ['id' => $eventId]);

        [$this->outputWidth, $this->outputHeight] = $this->getOutputDimensions($userId);

        $event = $this->loadEvent($eventId, $userId);
        $media = $this->loadIncludedMedia($eventId, $userId);

        if (count($media) < 2) {
            throw new \RuntimeException("Event {$eventId} has fewer than 2 included media items");
        }

        $userFolder = $this->rootFolder->getUserFolder($userId);
        $items      = $this->resolveFilePaths($media, $userFolder, $userId, $onDebug);

        if (count($items) < 2) {
            throw new \RuntimeException("Could not resolve enough media paths for event {$eventId}");
        }

        $tempDir = sys_get_temp_dir() . '/reel_' . $eventId . '_' . uniqid('', true);
        mkdir($tempDir, 0700, true);
        $renderSucceeded = false;

        try {
            // Pass 1: normalize each item to an intermediate clip
            $clips = $this->normalizeItems($items, $tempDir, $onProgress, $onDebug);

            // Pass 2: concatenate intermediates into final output
            if ($onProgress) { $onProgress(90); }
            $outputFolder    = $this->ensureOutputFolder($userFolder);
            $outputName      = $this->buildOutputFilename($event);
            $localOutputPath = $tempDir . '/final.mp4';

                $this->concatenateIntermediates(
                    $clips,
                    $localOutputPath,
                    $event,
                    $event['theme'] ?? null,
                    $userId,
                    $onDebug,
                );

            // Persist generated bytes via Nextcloud file API.
            $outputFile = $this->persistOutputFile($outputFolder, $outputName, $localOutputPath);
            $fileId     = $outputFile->getId();

            $this->updateEventVideoFileId($eventId, $userId, $fileId);

            $this->logger->info('Reel: render complete for event {id}, file {fileId}', [
                'id'     => $eventId,
                'fileId' => $fileId,
            ]);

            $renderSucceeded = true;

            return $fileId;

        } finally {
            if ($onDebug) {
                $onDebug('Debug mode: preserving temp dir ' . $tempDir);
            } else {
                $this->cleanupTempDir($tempDir);
            }
        }
    }

    // -------------------------------------------------------------------------
    // Pass 1: Normalize items to intermediates
    // -------------------------------------------------------------------------

    /**
     * Converts each item (photo or video, any format) to a normalized
     * H.264 1080p 30fps MP4 intermediate clip.
     */
    private function normalizeItems(array $items, string $tempDir, ?callable $onProgress = null, ?callable $onDebug = null): array {
        $clips = [];
        $total = count($items);

        for ($index = 0; $index < $total; $index++) {
            $item = $items[$index];
            $isLastItem = ($index === ($total - 1));
            $clipDuration = (float)($item['duration'] ?? 0.0);

            // Keep default stills at 2.5s, but give the final still extra hold time
            // so the end fade can run after ~1s unobstructed viewing.
            if (!$item['is_video'] && $isLastItem) {
                $clipDuration = max($clipDuration, 4.0);
            }

            if ($this->canBuildTriptychSegment($items, $index)) {
                $a = $items[$index];
                $b = $items[$index + 1];
                $c = $items[$index + 2];
                $outPath = $tempDir . '/clip_' . str_pad((string)$index, 4, '0', STR_PAD_LEFT) . '_triptych.mp4';
                $dirSeed = abs((int)crc32((string)$a['file_id'])) % 2;
                $dirs = $dirSeed === 0 ? ['up', 'down', 'up'] : ['down', 'up', 'down'];

                $triptychA = $this->prepareStillInputForLoop((string)$a['path'], $tempDir, $index, 'a');
                $triptychB = $this->prepareStillInputForLoop((string)$b['path'], $tempDir, $index, 'b');
                $triptychC = $this->prepareStillInputForLoop((string)$c['path'], $tempDir, $index, 'c');

                $cmd = $this->buildTriptychNormalizeCmd(
                    $triptychA,
                    $triptychB,
                    $triptychC,
                    $outPath,
                    3.2,
                    $dirs,
                );

                if ($onDebug) {
                    $onDebug('Triptych segment: files=' . basename((string)$a['path']) . ',' . basename((string)$b['path']) . ',' . basename((string)$c['path']) . ' dirs=' . implode('/', $dirs));
                    $onDebug("FFmpeg cmd: " . implode(' ', array_map('escapeshellarg', $cmd)));
                }
                $this->runFfmpeg($cmd);

                $clips[] = [
                    'path' => $outPath,
                    'duration' => 3.2,
                    'kind' => 'triptych',
                    'is_breaker' => true,
                    'motion' => 'triptych',
                    'run_state' => 'triptych',
                    'breaker_type' => 'triptych',
                ];

                if ($onProgress) {
                    $progress = (int)(1 + ((min($total, $index + 3)) / $total) * 88);
                    $onProgress($progress);
                }

                $index += 2;
                continue;
            }

            $outPath = $tempDir . '/clip_' . str_pad((string)$index, 4, '0', STR_PAD_LEFT) . '.mp4';

            $inputPath = $item['path'];

            // HEIC/AVIF: convert to a temp JPEG first since FFmpeg's HEIC
            // demuxer doesn't support -loop 1 and the loop video filter
            // produces black frames on this FFmpeg build.
            $tempJpeg = null;
            if (!$item['is_video']) {
                $ext = strtolower(pathinfo($inputPath, PATHINFO_EXTENSION));
                if (in_array($ext, ['heic', 'heif', 'avif'], true)) {
                    $tempJpeg = $tempDir . '/thumb_' . $index . '.jpg';
                    if ($onDebug) { $onDebug("HEIC→JPEG: {$inputPath} → {$tempJpeg}"); }
                    $this->convertToJpeg($inputPath, $tempJpeg);
                    $inputPath = $tempJpeg;
                }
            }

            $cmd = $item['is_video']
                ? $this->buildVideoNormalizeCmd($inputPath, $outPath, $clipDuration, (float)($item['start_at'] ?? 0.0), (int)($item['w'] ?? 0), (int)($item['h'] ?? 0), 'apple_subtle')
                : $this->buildPhotoNormalizeCmd($inputPath, $outPath, $clipDuration, $item['motion']);

            $this->logger->debug('Reel: normalizing item {i}/{total}', [
                'i'     => $index + 1,
                'total' => $total,
            ]);

            if ($onDebug) { $onDebug("FFmpeg cmd: " . implode(' ', array_map('escapeshellarg', $cmd))); }
            $this->runFfmpeg($cmd);
            $clips[] = [
                'path' => $outPath,
                'duration' => $clipDuration,
                'kind' => $item['is_video'] ? 'video' : 'photo',
                'is_breaker' => (bool)$item['is_video'],
                'motion' => (string)($item['motion']['run_motion'] ?? 'none'),
                'run_state' => $item['is_video'] ? 'video' : (string)($item['motion']['run_motion'] ?? 'none'),
                'breaker_type' => $item['is_video'] ? 'video' : 'none',
            ];

            // Report progress: clips take up 1-89%, Pass 2 gets 90-99%
            if ($onProgress) {
                $progress = (int)(1 + (($index + 1) / $total) * 88);
                $onProgress($progress);
            }
        }

        return $clips;
    }

    private function canBuildTriptychSegment(array $items, int $startIndex): bool {
        if (!isset($items[$startIndex + 2])) {
            return false;
        }

        for ($i = $startIndex; $i <= $startIndex + 2; $i++) {
            $it = $items[$i];
            if (!empty($it['is_video'])) {
                return false;
            }

            $w = (int)($it['w'] ?? 0);
            $h = (int)($it['h'] ?? 0);
            if ($w <= 0 || $h <= 0 || $w >= $h) {
                return false;
            }
        }

        return true;
    }

    /**
     * Normalize a video clip to standard intermediate format.
     * Handles any input codec/container.
     */
    private function buildVideoNormalizeCmd(string $inputPath, string $outputPath, float $duration, float $startAt = 0.0, int $videoW = 0, int $videoH = 0, string $motionStyle = 'apple_subtle'): array {
        $cmd = [
            'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
            '-i', $inputPath,
            '-ignore_unknown',  // don't puke out on unknown audio or video streams
        ];

        if ($startAt > 0.0) {
            $cmd[] = '-ss';
            $cmd[] = number_format($startAt, 3, '.', '');
        }

        // For apple_subtle, use a blurred fill background instead of black bars
        // when the video aspect ratio differs from the output (e.g. portrait video
        // in a landscape frame, or landscape video in a portrait frame).
        if ($motionStyle === 'apple_subtle' && $videoW > 0 && $videoH > 0) {
            $outW = $this->outputWidth();
            $outH = $this->outputHeight();
            $targetAspect = $this->targetAspect();
            $videoAspect  = $videoW / $videoH;
            $aspectDiff   = abs($videoAspect - $targetAspect) / $targetAspect;

            if ($aspectDiff > 0.02) {
                // Fit the video into the output frame (no crop), letterbox/pillarbox.
                if ($videoAspect >= $targetAspect) {
                    $fitW = $outW;
                    $fitH = (int)(round($outW / $videoAspect / 2) * 2);
                } else {
                    $fitH = $outH;
                    $fitW = (int)(round($outH * $videoAspect / 2) * 2);
                }
                $overlayX = (int)(($outW - $fitW) / 2);
                $overlayY = (int)(($outH - $fitH) / 2);

                $fc = implode(';', [
                    '[0:v]split=2[bgsrc][fgsrc]',
                    "[bgsrc]scale=w={$outW}:h={$outH}:force_original_aspect_ratio=increase,crop={$outW}:{$outH},gblur=sigma=36,eq=saturation=0.92:brightness=-0.02[bg]",
                    "[fgsrc]scale=w={$fitW}:h={$fitH}:flags=lanczos[fg]",
                    "[bg][fg]overlay=x={$overlayX}:y={$overlayY},setsar=1[vout]",
                ]);

                return array_merge($cmd, [
                    '-t', number_format($duration, 3, '.', ''),
                    '-filter_complex', $fc,
                    '-map', '[vout]',
                    '-map', '0:a:0?',     // first audio stream only, if exists
                    '-af', 'aformat=sample_rates=44100:channel_layouts=stereo,asetpts=PTS-STARTPTS',
                    '-r', (string)self::FPS,
                    '-c:v', 'libx264',
                    '-preset', 'fast',
                    '-crf', '18',
                    '-c:a', 'aac',
                    '-ar', '44100',
                    '-ac', '2',
                    '-movflags', '+faststart',
                    $outputPath,
                ]);
            }
        }

        return array_merge($cmd, [
            '-t', number_format($duration, 3, '.', ''),
            '-vf', $this->scaleFilter(),
            '-map', '0:v',
            '-map', '0:a:0?',     // first audio stream only, if exists
            '-af', 'aformat=sample_rates=44100:channel_layouts=stereo,asetpts=PTS-STARTPTS',
            '-r', (string)self::FPS,
            '-c:v', 'libx264',
            '-preset', 'fast',
            '-crf', '18',           // high quality intermediate
            '-c:a', 'aac',
            '-ar', '44100',
            '-ac', '2',
            '-movflags', '+faststart',
            $outputPath,
        ]);
    }

    /**
     * Normalize a photo to a short video clip with a subtle Ken Burns zoom.
     * Adds a silent audio track so all intermediates are uniform (video+audio).
     */
    private function buildPhotoNormalizeCmd(string $inputPath, string $outputPath, float $duration, array $motion): array {
        $frameCount = (int)ceil($duration * self::FPS);

        $style = (string)($motion['style'] ?? 'apple_subtle');
        $zoomStartRaw = (float)($motion['zoom_start'] ?? 1.0);
        $zoomEndRaw = (float)($motion['zoom_end'] ?? 1.0);
        $zoomStart = number_format($zoomStartRaw, 4, '.', '');
        $zoomEnd = number_format($zoomEndRaw, 4, '.', '');
        $fx = number_format((float)$motion['fx'], 4, '.', '');
        $fy = number_format((float)($motion['fy'] ?? 0.5), 4, '.', '');
        $mode = (string)($motion['mode'] ?? 'zoom');
        $framesMinusOne = max(1, $frameCount - 1);

        // Cover scale preserves aspect ratio exactly without warping.
        // For pan modes we intentionally pan on the uncropped scaled frame,
        // otherwise movement range is tiny after center-crop.
        $outW = $this->outputWidth();
        $outH = $this->outputHeight();
        $targetAspect = $this->targetAspect();
        $coverScale = "scale=w='if(gte(iw/ih," . $targetAspect . "),-2," . $outW . ")':h='if(gte(iw/ih," . $targetAspect . ")," . $outH . ",-2)'";
        $coverCrop = 'crop=' . $outW . ':' . $outH . ':(iw-' . $outW . ')/2:(ih-' . $outH . ')/2';

        $t = '(n/' . $framesMinusOne . ')';
        $zoomEase = $this->easeInOutCubicExpr($t);

        if ($style === 'apple_subtle') {
            // Clamp zoom range to subtle values.
            $appleZoomStart = $this->clamp($zoomStartRaw, 0.98, 1.06);
            $appleZoomEnd   = $this->clamp($zoomEndRaw,   0.98, 1.06);

            // Compute the fit dimensions: the pixel box the photo occupies when
            // letterboxed/pillarboxed into the output frame (no cropping).
            // Dimensions must be even (required by libx264).
            $imageAspect = (float)($motion['image_aspect'] ?? $targetAspect);
            if ($imageAspect >= $targetAspect) {
                $fitW = $outW;
                $fitH = (int)(round($outW / $imageAspect / 2) * 2);
            } else {
                $fitH = $outH;
                $fitW = (int)(round($outH * $imageAspect / 2) * 2);
            }

            // zoompan: input is pre-scaled to fitW×fitH; output is always fitW×fitH.
            // zoom=1.0 → shows the full fitW×fitH (no zoom), zoom>1 → zoomed in.
            // The overlay onto the blurred background is always at a fixed position.
            $appleZoomStartFmt = number_format($appleZoomStart, 4, '.', '');
            $appleZoomEndFmt   = number_format($appleZoomEnd,   4, '.', '');

            // Per-frame zoom interpolation.
            $zpZoom = "{$appleZoomStartFmt}+({$appleZoomEndFmt}-{$appleZoomStartFmt})*{$zoomEase}";

            $focusX = number_format($this->clamp((float)($motion['fx'] ?? 0.5), 0.12, 0.88), 4, '.', '');
            $focusY = number_format($this->clamp((float)($motion['fy'] ?? 0.5), 0.12, 0.88), 4, '.', '');

            // Overlay is constant: fit box always centered in output frame.
            $overlayX = (int)(($outW - $fitW) / 2);
            $overlayY = (int)(($outH - $fitH) / 2);

            $fitScale = "scale=w={$fitW}:h={$fitH}:flags=lanczos";
            // Animated scale + crop avoids zoompan coordinate stepping jitter.
            $animatedScale = "scale=w='trunc(iw*({$zpZoom})/2)*2':h='trunc(ih*({$zpZoom})/2)*2':flags=lanczos:eval=frame";
            // Keep zoom centered on the focus point, then clamp to image bounds.
            $cropX = "max(0,min(iw-{$fitW},iw*({$focusX})-{$fitW}/2))";
            $cropY = "max(0,min(ih-{$fitH},ih*({$focusY})-{$fitH}/2))";
            $animatedCrop = "crop={$fitW}:{$fitH}:'{$cropX}':'{$cropY}'";

            $fc = implode(';', [
                "[0:v]split=2[bgsrc][fgsrc]",
                "[bgsrc]scale=w={$outW}:h={$outH}:force_original_aspect_ratio=increase,crop={$outW}:{$outH},gblur=sigma=36,eq=saturation=0.92:brightness=-0.02[bg]",
                "[fgsrc]{$fitScale},{$animatedScale},{$animatedCrop}[fg]",
                "[bg][fg]overlay=x={$overlayX}:y={$overlayY},setsar=1[vout]",
            ]);

            return [
                'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
                '-loop', '1',
                '-i', $inputPath,
                '-f', 'lavfi', '-i', 'anullsrc=channel_layout=stereo:sample_rate=44100',
                '-t', number_format($duration, 2, '.', ''),
                '-filter_complex', $fc,
                '-map', '[vout]',
                '-map', '1:a',
                '-r', (string)self::FPS,
                '-c:v', 'libx264',
                '-preset', 'fast',
                '-crf', '18',
                '-c:a', 'aac',
                '-ar', '44100',
                '-ac', '2',
                '-shortest',
                '-movflags', '+faststart',
                $outputPath,
            ];
        }

        // For explicit pan modes, animate crop directly over the full clip duration.
        // This avoids zoompan timing quirks with looped still-image inputs.
        if ($mode === 'pan_x') {
            $fxStart = number_format((float)($motion['fx_start'] ?? 0.08), 4, '.', '');
            $fxEnd = number_format((float)($motion['fx_end'] ?? 0.92), 4, '.', '');
            $fyFixed = number_format((float)($motion['fy'] ?? 0.5), 4, '.', '');
            $panT = '(n/' . $framesMinusOne . ')';
            $panEase = $this->easeInOutCubicExpr($panT);
            $fxExpr = "{$fxStart}+({$fxEnd}-{$fxStart})*{$panEase}";
            $cropX = "max(0,min(iw-" . $outW . ",(iw-" . $outW . ")*({$fxExpr})))";
            $cropY = "max(0,min(ih-" . $outH . ",(ih-" . $outH . ")*({$fyFixed})))";
            $panCrop = "crop=" . $outW . ":" . $outH . ":'{$cropX}':'{$cropY}'";
            $vf = implode(',', [$coverScale, $panCrop, 'setsar=1']);

            return [
                'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
                '-loop', '1',
                '-i', $inputPath,
                '-f', 'lavfi', '-i', 'anullsrc=channel_layout=stereo:sample_rate=44100',
                '-t', number_format($duration, 2, '.', ''),
                '-vf', $vf,
                '-r', (string)self::FPS,
                '-c:v', 'libx264',
                '-preset', 'fast',
                '-crf', '18',
                '-c:a', 'aac',
                '-ar', '44100',
                '-ac', '2',
                '-shortest',
                '-movflags', '+faststart',
                $outputPath,
            ];
        }

        if ($mode === 'pan_y') {
            $fyStart = number_format((float)($motion['fy_start'] ?? 0.08), 4, '.', '');
            $fyEnd = number_format((float)($motion['fy_end'] ?? 0.92), 4, '.', '');
            $fxFixed = number_format((float)($motion['fx'] ?? 0.5), 4, '.', '');
            $panT = '(n/' . $framesMinusOne . ')';
            $panEase = $this->easeInOutCubicExpr($panT);
            $fyExpr = "{$fyStart}+({$fyEnd}-{$fyStart})*{$panEase}";
            $cropX = "max(0,min(iw-" . $outW . ",(iw-" . $outW . ")*({$fxFixed})))";
            $cropY = "max(0,min(ih-" . $outH . ",(ih-" . $outH . ")*({$fyExpr})))";
            $panCrop = "crop=" . $outW . ":" . $outH . ":'{$cropX}':'{$cropY}'";
            $vf = implode(',', [$coverScale, $panCrop, 'setsar=1']);

            return [
                'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
                '-loop', '1',
                '-i', $inputPath,
                '-f', 'lavfi', '-i', 'anullsrc=channel_layout=stereo:sample_rate=44100',
                '-t', number_format($duration, 2, '.', ''),
                '-vf', $vf,
                '-r', (string)self::FPS,
                '-c:v', 'libx264',
                '-preset', 'fast',
                '-crf', '18',
                '-c:a', 'aac',
                '-ar', '44100',
                '-ac', '2',
                '-shortest',
                '-movflags', '+faststart',
                $outputPath,
            ];
        }

        $zoomExpr = "{$zoomStart}+({$zoomEnd}-{$zoomStart})*{$zoomEase}";
        // Animated scale + crop avoids zoompan's integer coordinate stepping jitter.
        $animatedScale = "scale=w='trunc(iw*({$zoomExpr})/2)*2':h='trunc(ih*({$zoomExpr})/2)*2':flags=lanczos:eval=frame";
        $cropX = "max(0,min(iw-" . $outW . ",(iw-" . $outW . ")*({$fx})))";
        $cropY = "max(0,min(ih-" . $outH . ",(ih-" . $outH . ")*({$fy})))";
        $animatedCrop = "crop=" . $outW . ":" . $outH . ":'{$cropX}':'{$cropY}'";

        $vf = implode(',', [$coverScale, $animatedScale, $animatedCrop, 'setsar=1']);

        return [
            'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
            '-loop', '1',
            '-i', $inputPath,
            '-f', 'lavfi', '-i', 'anullsrc=channel_layout=stereo:sample_rate=44100',
            '-t', number_format($duration, 2, '.', ''),
            '-vf', $vf,
            '-r', (string)self::FPS,
            '-c:v', 'libx264',
            '-preset', 'fast',
            '-crf', '18',
            '-c:a', 'aac',
            '-ar', '44100',
            '-ac', '2',
            '-shortest',
            '-movflags', '+faststart',
            $outputPath,
        ];
    }

    /**
     * Convert a HEIC/AVIF image to JPEG using Imagick.
     * This is necessary because FFmpeg's HEIC demuxer doesn't support -loop 1.
     */
    private function convertToJpeg(string $inputPath, string $outputPath): void {
        $imagick = new \Imagick();
        $imagick->readImage($inputPath . '[0]'); // [0] = first frame only
        $imagick->setImageFormat('jpeg');
        $imagick->setImageCompressionQuality(92);
        $imagick->writeImage($outputPath);
        $imagick->clear();
        $imagick->destroy();
    }

    /**
     * Scale + letterbox filter to fit any input into 1080p with black bars.
     */
    private function scaleFilter(): string {
        $outW = $this->outputWidth();
        $outH = $this->outputHeight();
        return "scale=w=" . $outW . ":h=" . $outH
            . ":force_original_aspect_ratio=decrease"
            . ",pad=" . $outW . ":" . $outH
            . ":(ow-iw)/2:(oh-ih)/2:black"
            . ",setsar=1";
    }

    // -------------------------------------------------------------------------
    // Pass 2: Concatenate with transitions → H.264 intermediate
    // Pass 3: Final encode with music, titles, fade → H.265 output
    // -------------------------------------------------------------------------
 
    private function concatenateIntermediates(array $clips, string $outputPath, array $event, ?string $theme, string $userId, ?callable $onDebug = null): void {
        $count = count($clips);
 
        if ($count === 0) {
            throw new \RuntimeException('No clips to concatenate');
        }
 
        if ($count === 1) {
            // Single clip: skip transition pass, go straight to final encode
            $this->runFinalEncodePass(
                $clips[0]['path'],
                (float)$clips[0]['duration'],
                $outputPath,
                $event,
                $theme,
                $userId,
                $onDebug,
            );
            return;
        }
 
        // Pass 2: transitions only → H.264 stitched (low memory, no music/x265)
        $tempDir = dirname($outputPath);
        $stitchedPath = $tempDir . '/stitched.mp4';
 
        $this->runTransitionStitchPass($clips, $stitchedPath, $onDebug);
 
        // Pass 3: final encode with music, titles, fade → H.265
        $totalDuration = $this->computeTimelineDuration($clips);
        $this->runFinalEncodePass(
            $stitchedPath,
            $totalDuration,
            $outputPath,
            $event,
            $theme,
            $userId,
            $onDebug,
        );
    }
        /**
     * Pass 2: stitch all intermediate clips together with xfade transitions.
     *
     * Uses a binary merge tree (tournament bracket) so each clip is re-encoded
     * at most ceil(log2(n)) times rather than n times. For 25 clips that's 5
     * generations instead of 24, and for 130 clips it's 7 instead of 129.
     *
     * Memory is bounded: each FFmpeg call has exactly 2 inputs.
     * Quality loss is bounded: at most ceil(log2(n)) lossy re-encodes per frame.
     *
     * Each "segment" in the working set carries:
     *   path      — path to the encoded file
     *   duration  — total duration of the encoded file
     *   clips     — the original $clips[] entries it was built from, in order
     *               (needed to pick the correct transition at the join point)
     */
    private function runTransitionStitchPass(array $clips, string $outputPath, ?callable $onDebug = null): void {
        $count = count($clips);
        $tempDir = dirname($outputPath);
        $stepCounter = 0;
 
        // Initialise the working set: each clip is its own segment.
        $segments = [];
        foreach ($clips as $clip) {
            $segments[] = [
                'path'     => (string)$clip['path'],
                'duration' => (float)$clip['duration'],
                'clips'    => [$clip],
                'owned'    => false,   // original clip files are not ours to delete
            ];
        }
 
        // Merge pairs until one segment remains.
        while (count($segments) > 1) {
            $nextRound = [];
            $segCount  = count($segments);
 
            for ($j = 0; $j < $segCount; $j += 2) {
                if ($j + 1 >= $segCount) {
                    // Odd one out — carry it forward unchanged.
                    $nextRound[] = $segments[$j];
                    continue;
                }
 
                $left  = $segments[$j];
                $right = $segments[$j + 1];
 
                // The transition at the join point is determined by the last clip
                // of the left segment and the first clip of the right segment.
                // We use the original clip index in the global array for pickTransitionSpec.
                $leftLastClip  = end($left['clips']);
                $rightFirstClip = reset($right['clips']);
                $globalRightIndex = array_search($rightFirstClip, $clips, true);
                if ($globalRightIndex === false) {
                    // Fallback: use count of left clips as a proxy index.
                    $globalRightIndex = count($left['clips']);
                }
 
                $transitionSpec     = $this->pickTransitionSpec($leftLastClip, $rightFirstClip, (int)$globalRightIndex);
                $transitionDuration = (float)$transitionSpec['duration'];
                $offset             = max(0.0, $left['duration'] - $transitionDuration);
 
                $stepCounter++;
                $isFinalMerge = (count($segments) === 2 && $j === 0);
                $mergedPath   = $isFinalMerge
                    ? $outputPath
                    : $tempDir . '/merge_' . $stepCounter . '.mp4';
 
                $filterParts = [
                    '[0:v]settb=AVTB,format=yuv420p[va]',
                    '[1:v]settb=AVTB,format=yuv420p[vb]',
                ];
 
                if (($transitionSpec['type'] ?? '') === 'triptych_strip') {
                    $invert    = !empty($transitionSpec['invert']);
                    $leftDir   = $invert ? 'wiperight' : 'wipeleft';
                    $midDir    = $invert ? 'wipeleft'  : 'wiperight';
                    $offsetStr = number_format($offset, 3, '.', '');
 
                    $filterParts[] = '[va]split=3[a0][a1][a2]';
                    $filterParts[] = '[vb]split=3[b0][b1][b2]';
                    $filterParts[] = '[a0]crop=iw/3:ih:0:0[sa0]';
                    $filterParts[] = '[a1]crop=iw/3:ih:iw/3:0[sa1]';
                    $filterParts[] = '[a2]crop=iw/3:ih:2*iw/3:0[sa2]';
                    $filterParts[] = '[b0]crop=iw/3:ih:0:0[sb0]';
                    $filterParts[] = '[b1]crop=iw/3:ih:iw/3:0[sb1]';
                    $filterParts[] = '[b2]crop=iw/3:ih:2*iw/3:0[sb2]';
                    $filterParts[] = "[sa0][sb0]xfade=transition={$leftDir}:duration={$transitionDuration}:offset={$offsetStr}[x0]";
                    $filterParts[] = "[sa1][sb1]xfade=transition={$midDir}:duration={$transitionDuration}:offset={$offsetStr}[x1]";
                    $filterParts[] = "[sa2][sb2]xfade=transition={$leftDir}:duration={$transitionDuration}:offset={$offsetStr}[x2]";
                    $filterParts[] = '[x0][x1][x2]hstack=inputs=3[vout]';
                } else {
                    $transition  = (string)$transitionSpec['name'];
                    $filterParts[] = "[va][vb]xfade=transition={$transition}"
                        . ':duration=' . number_format($transitionDuration, 3, '.', '')
                        . ':offset='   . number_format($offset, 3, '.', '') . '[vout]';
                }
 
                // Audio crossfade at the join point.
                $leftAudioDur  = max(0.05, $left['duration']  - ($transitionDuration / 2.0));
                $rightAudioDur = max(0.05, $right['duration'] - ($transitionDuration / 2.0));
                $crossfade     = max(0.02, min(self::AUDIO_CROSSFADE_SECONDS,
                    min($leftAudioDur, $rightAudioDur) * 0.45));
 
                $filterParts[] = '[0:a]aformat=sample_rates=44100:channel_layouts=stereo'
                    . ',atrim=duration=' . number_format($leftAudioDur, 3, '.', '')
                    . ',asetpts=PTS-STARTPTS[al]';
                $filterParts[] = '[1:a]aformat=sample_rates=44100:channel_layouts=stereo'
                    . ',atrim=duration=' . number_format($rightAudioDur, 3, '.', '')
                    . ',asetpts=PTS-STARTPTS[ar]';
                $filterParts[] = '[al][ar]acrossfade=d='
                    . number_format($crossfade, 3, '.', '') . ':o=0:c1=tri:c2=tri[aout]';
 
                $cmd = [
                    'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
                    '-i', $left['path'],
                    '-i', $right['path'],
                    '-filter_complex', implode(';', $filterParts),
                    '-map', '[vout]',
                    '-map', '[aout]',
                    '-c:v', 'libx264',
                    '-preset', 'fast',
                    '-crf', '16',
                    '-c:a', 'aac',
                    '-ar', '44100',
                    '-ac', '2',
                    '-movflags', '+faststart',
                    $mergedPath,
                ];
 
                if ($onDebug) {
                    $leftLabel  = basename($left['path']);
                    $rightLabel = basename($right['path']);
                    $onDebug("FFmpeg merge step {$stepCounter} ({$leftLabel} + {$rightLabel}): "
                        . implode(' ', array_map('escapeshellarg', $cmd)));
                }
 
                $this->runFfmpeg($cmd);
 
                // Clean up temp files we own (not original clip files).
                if ($left['owned'])  { @unlink($left['path']); }
                if ($right['owned']) { @unlink($right['path']); }
 
                $mergedDuration = $left['duration'] + $right['duration'] - $transitionDuration;
 
                $nextRound[] = [
                    'path'     => $mergedPath,
                    'duration' => $mergedDuration,
                    'clips'    => array_merge($left['clips'], $right['clips']),
                    'owned'    => true,
                ];
            }
 
            $segments = $nextRound;
        }
 
        $this->logger->info('Reel: transition stitch pass complete ({n} merge steps)', ['n' => $stepCounter]);
    }

    /**
     * Pass 3: take a single stitched video, add titles, music, outro fade, encode H.265.
     * Only 1 video input → x265 lookahead is tiny, peak memory is minimal.
     */
    private function runFinalEncodePass(
        string $stitchedPath,
        float $timelineDuration,
        string $outputPath,
        array $event,
        ?string $theme,
        string $userId,
        ?callable $onDebug = null,
    ): void {
        $musicPath = $this->getMusicPath($theme, $userId);
        $hasMusic  = $musicPath && file_exists($musicPath);
 
        $cmd = ['ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
            '-i', $stitchedPath,
        ];
        if ($hasMusic) {
            $cmd[] = '-stream_loop'; $cmd[] = '-1';
            $cmd[] = '-i'; $cmd[] = $musicPath;
        }
 
        $filterParts = [];
        $videoLabel  = '0:v';
 
        // Title overlays
        $introTitle = trim((string)($event['title'] ?? ''));
        $introDate  = '';
        if (!empty($event['date_start'])) {
            $dt = (new \DateTimeImmutable('@' . (int)$event['date_start']))
                ->setTimezone(new \DateTimeZone(date_default_timezone_get()));
            $introDate = $dt->format('F j, Y');
        }
 
        if ($introTitle !== '') {
            $titleEsc   = $this->escapeDrawtext($introTitle);
            $enableExpr = "lte(t," . number_format(self::INTRO_TEXT_DURATION_SECONDS, 3, '.', '') . ")";
            $filterParts[] = "[{$videoLabel}]drawtext=font=Sans:text='{$titleEsc}':fontcolor=white"
                . ":fontsize=64:borderw=3:bordercolor=black:x=(w-text_w)/2:y=(h*5/6-text_h-8)"
                . ":enable='{$enableExpr}'[vtitle]";
            $videoLabel = 'vtitle';
        }
 
        if ($introDate !== '') {
            $dateEsc    = $this->escapeDrawtext($introDate);
            $enableExpr = "lte(t," . number_format(self::INTRO_TEXT_DURATION_SECONDS, 3, '.', '') . ")";
            $filterParts[] = "[{$videoLabel}]drawtext=font=Sans:text='{$dateEsc}':fontcolor=white"
                . ":fontsize=40:borderw=3:bordercolor=black:x=(w-text_w)/2:y=(h*5/6+8)"
                . ":enable='{$enableExpr}'[vdate]";
            $videoLabel = 'vdate';
        }
 
        // Outro fade to black — freeze-extend tail if needed so fade has room
        $outroFadeDuration = self::OUTRO_VIDEO_FADE_SECONDS;
        $fadeStart         = max(0.0, $timelineDuration - $outroFadeDuration);
        $tailHold          = max(0.0, ($fadeStart + $outroFadeDuration) - $timelineDuration);
 
        if ($tailHold > 0.0) {
            $filterParts[] = "[{$videoLabel}]tpad=stop_mode=clone:stop_duration="
                . number_format($tailHold, 3, '.', '') . "[vhold]";
            $videoLabel = 'vhold';
        }
 
        $filterParts[] = "[{$videoLabel}]fade=t=out:st=" . number_format($fadeStart, 3, '.', '')
            . ":d=" . number_format($outroFadeDuration, 3, '.', '') . "[voutro]";
        $videoLabel = 'voutro';
 
        $totalDuration = $fadeStart + $outroFadeDuration;
 
        // Music + natural audio with sidechain ducking
        $audioLabel = '0:a';
        if ($hasMusic) {
            $musicIdx       = 1;
            $fadeDuration   = min(self::OUTRO_VIDEO_FADE_SECONDS, $totalDuration);
            $musicFadeStart = max(0.0, $totalDuration - $fadeDuration);
            $filterParts[] = "[{$musicIdx}:a]aresample=async=1:first_pts=0"
                . ",atrim=duration=" . number_format($totalDuration, 3, '.', '')
                . ",volume=" . self::MUSIC_BASE_VOLUME
                . ",afade=t=out:st=" . number_format($musicFadeStart, 3, '.', '')
                . ":d=" . number_format($fadeDuration, 3, '.', '') . "[music]";
            $filterParts[] = "[0:a]asplit=2[anat_mix][anat_sc]";
            $filterParts[] = "[music][anat_sc]sidechaincompress=threshold=0.03:ratio=7:attack=20:release=250[ducked]";
            $filterParts[] = "[ducked][anat_mix]amix=inputs=2:duration=longest:dropout_transition=0"
                . ":weights=" . self::MUSIC_DUCKED_VOLUME . " 1:normalize=0[aout]";
            $audioLabel = 'aout';
        }
 
        if (!empty($filterParts)) {
            $cmd[] = '-filter_complex';
            $cmd[] = implode(';', $filterParts);
        }
 
        $cmd[] = '-map'; $cmd[] = "[{$videoLabel}]";
        $cmd[] = '-map'; $cmd[] = $hasMusic ? "[{$audioLabel}]" : "0:a";
        $cmd   = array_merge($cmd, [
            '-c:v', 'libx265',
            '-crf', '23',
            '-preset', 'fast',
            '-tag:v', 'hvc1',
            '-c:a', 'aac',
            '-b:a', '192k',
            '-movflags', '+faststart',
            $outputPath,
        ]);
 
        $this->logger->info('Reel: running final encode pass (duration={d}s)', [
            'd' => number_format($totalDuration, 1),
        ]);
        if ($onDebug) {
            $onDebug("FFmpeg final encode cmd: " . implode(' ', array_map('escapeshellarg', $cmd)));
        }
        $this->runFfmpeg($cmd);
    }
 
    private function computeTimelineDuration(array $clips): float {
        $count = count($clips);
        if ($count === 0) {
            return 0.0;
        }
 
        $accumulated = (float)$clips[0]['duration'];
        for ($i = 1; $i < $count; $i++) {
            $spec = $this->pickTransitionSpec($clips[$i - 1], $clips[$i], $i);
            $accumulated += (float)$clips[$i]['duration'] - (float)$spec['duration'];
        }
        return $accumulated;
    }

    private function escapeDrawtext(string $text): string {
        $escaped = str_replace('\\', '\\\\', $text);
        $escaped = str_replace(':', '\\:', $escaped);
        $escaped = str_replace("'", "\\'", $escaped);
        return str_replace('%', '\\%', $escaped);
    }

    private function pickTransitionSpec(array $prevClip, array $nextClip, int $index): array {
        $prevKind = (string)($prevClip['kind'] ?? 'photo');
        $nextKind = (string)($nextClip['kind'] ?? 'photo');
        $prevBreakerType = (string)($prevClip['breaker_type'] ?? (!empty($prevClip['is_breaker']) ? $prevKind : 'none'));
        $nextBreakerType = (string)($nextClip['breaker_type'] ?? (!empty($nextClip['is_breaker']) ? $nextKind : 'none'));
        $prevRun = (string)($prevClip['run_state'] ?? $prevClip['motion'] ?? 'none');
        $nextRun = (string)($nextClip['run_state'] ?? $nextClip['motion'] ?? 'none');

        // Triptych transitions get strip-wise opposite-direction wipes.
        if ($prevKind === 'triptych' || $nextKind === 'triptych') {
            $invertPattern = ($prevKind === 'triptych' && $nextKind !== 'triptych');
            return [
                'name' => 'triptych_strip',
                'type' => 'triptych_strip',
                'invert' => $invertPattern,
                'duration' => 0.42,
            ];
        }

        // Explicit breaker-aware transition policy.
        if ($prevBreakerType === 'video' && $nextBreakerType === 'video') {
            return ['name' => 'dissolve', 'duration' => 0.34];
        }
        if ($nextBreakerType === 'video') {
            return ['name' => 'fadeblack', 'duration' => 0.36];
        }
        if ($prevBreakerType === 'video') {
            return ['name' => $this->runToHardTransition($nextRun), 'duration' => 0.34];
        }

        if (!empty($prevClip['is_breaker']) || !empty($nextClip['is_breaker'])) {
            $runHint = !empty($nextClip['is_breaker']) ? $prevRun : $nextRun;
            return ['name' => $this->runToHardTransition($runHint), 'duration' => 0.34];
        }

        // Within same run: reinforce motion continuity. Run change: use stronger hard transition.
        if ($prevRun !== 'none' && $prevRun === $nextRun) {
            return ['name' => $this->runToSoftTransition($prevRun), 'duration' => 0.30];
        }

        if ($nextRun !== 'none') {
            return ['name' => $this->runToHardTransition($nextRun), 'duration' => 0.32];
        }

        $variants = ['smoothleft', 'smoothright', 'smoothup', 'smoothdown'];
        return ['name' => $variants[$index % count($variants)], 'duration' => 0.30];
    }

    private function runToSoftTransition(string $runState): string {
        return match ($runState) {
            'pan_left' => 'slideleft',
            'pan_right' => 'slideright',
            'zoom_in' => 'smoothup',
            'zoom_out' => 'smoothdown',
            default => 'dissolve',
        };
    }

    private function runToHardTransition(string $runState): string {
        return match ($runState) {
            'pan_left' => 'wipeleft',
            'pan_right' => 'wiperight',
            'zoom_in' => 'wipeup',
            'zoom_out' => 'wipedown',
            default => 'fade',
        };
    }

    private function buildTriptychNormalizeCmd(
        string $inputA,
        string $inputB,
        string $inputC,
        string $outputPath,
        float $duration,
        array $dirs,
    ): array {
        $frameCount = (int)ceil($duration * self::FPS);
        $framesMinusOne = max(1, $frameCount - 1);
        $outW = $this->outputWidth();
        $outH = $this->outputHeight();
        $colWidth = (int)floor($outW / 3);
        $scaledH = (int)ceil(($outH * 1.12) / 2) * 2;
        $panT = '(n/' . $framesMinusOne . ')';
        $panEase = $this->easeInOutCubicExpr($panT);

        $yExpr1 = $this->triptychYExpr($dirs[0] ?? 'up', $panEase);
        $yExpr2 = $this->triptychYExpr($dirs[1] ?? 'down', $panEase);
        $yExpr3 = $this->triptychYExpr($dirs[2] ?? 'up', $panEase);

        $fc = implode(';', [
            "[0:v]scale=-2:{$scaledH},crop={$colWidth}:" . $outH . ":(iw-{$colWidth})/2:'{$yExpr1}'[v0]",
            "[1:v]scale=-2:{$scaledH},crop={$colWidth}:" . $outH . ":(iw-{$colWidth})/2:'{$yExpr2}'[v1]",
            "[2:v]scale=-2:{$scaledH},crop={$colWidth}:" . $outH . ":(iw-{$colWidth})/2:'{$yExpr3}'[v2]",
            "[v0][v1][v2]hstack=inputs=3[stack]",
            "[stack]drawbox=x={$colWidth}:y=0:w=2:h=" . $outH . ":color=black@0.95:t=fill,drawbox=x=" . ($colWidth * 2) . ":y=0:w=2:h=" . $outH . ":color=black@0.95:t=fill,setsar=1[vout]",
        ]);

        return [
            'ffmpeg', '-y', '-nostdin', '-hide_banner', '-loglevel', 'error',
            '-loop', '1', '-i', $inputA,
            '-loop', '1', '-i', $inputB,
            '-loop', '1', '-i', $inputC,
            '-f', 'lavfi', '-i', 'anullsrc=channel_layout=stereo:sample_rate=44100',
            '-t', number_format($duration, 2, '.', ''),
            '-filter_complex', $fc,
            '-map', '[vout]',
            '-map', '3:a',
            '-r', (string)self::FPS,
            '-c:v', 'libx264',
            '-preset', 'fast',
            '-crf', '18',
            '-c:a', 'aac',
            '-ar', '44100',
            '-ac', '2',
            '-shortest',
            '-movflags', '+faststart',
            $outputPath,
        ];
    }

    private function triptychYExpr(string $dir, string $panEaseExpr): string {
        $start = $dir === 'up' ? 0.80 : 0.20;
        $end = $dir === 'up' ? 0.20 : 0.80;
        $startStr = number_format($start, 4, '.', '');
        $endStr = number_format($end, 4, '.', '');
        $focusExpr = "{$startStr}+({$endStr}-{$startStr})*{$panEaseExpr}";
        $outH = $this->outputHeight();
        return "max(0,min(ih-" . $outH . ",(ih-" . $outH . ")*({$focusExpr})))";
    }

    private function prepareStillInputForLoop(string $inputPath, string $tempDir, int $index, string $suffix): string {
        $ext = strtolower(pathinfo($inputPath, PATHINFO_EXTENSION));
        if (!in_array($ext, ['heic', 'heif', 'avif'], true)) {
            return $inputPath;
        }

        $tempJpeg = $tempDir . '/triptych_' . $index . '_' . $suffix . '.jpg';
        $this->convertToJpeg($inputPath, $tempJpeg);
        return $tempJpeg;
    }

    // -------------------------------------------------------------------------
    // Data loading
    // -------------------------------------------------------------------------

    private function loadEvent(int $eventId, string $userId): array {
        $qb = $this->db->getQueryBuilder();
        $qb->select('*')
            ->from('reel_events')
            ->where($qb->expr()->eq('id',       $qb->createNamedParameter($eventId, IQueryBuilder::PARAM_INT)))
            ->andWhere($qb->expr()->eq('user_id', $qb->createNamedParameter($userId)));

        $result = $qb->executeQuery();
        $row    = $result->fetch();
        $result->closeCursor();

        if (!$row) {
            throw new \RuntimeException("Event {$eventId} not found for user {$userId}");
        }

        return $row;
    }

    private function loadIncludedMedia(int $eventId, string $userId): array {
        $qb = $this->db->getQueryBuilder();
        $qb->select('m.file_id', 'm.sort_order', 'm.edit_settings', 'mem.isvideo', 'mem.video_duration', 'mem.liveid', 'mem.w', 'mem.h')
            ->from('reel_event_media', 'm')
            ->innerJoin('m', 'memories', 'mem', $qb->expr()->eq('m.file_id', 'mem.fileid'))
            ->where($qb->expr()->eq('m.event_id', $qb->createNamedParameter($eventId,  IQueryBuilder::PARAM_INT)))
            ->andWhere($qb->expr()->eq('m.user_id',   $qb->createNamedParameter($userId)))
            ->andWhere($qb->expr()->eq('m.included',  $qb->createNamedParameter(true, IQueryBuilder::PARAM_BOOL)))
            ->orderBy('m.sort_order', 'ASC');

        $result = $qb->executeQuery();
        $rows   = $result->fetchAll();
        $result->closeCursor();

        foreach ($rows as &$row) {
            $settings = !empty($row['edit_settings'])
                ? (json_decode($row['edit_settings'], true) ?? [])
                : [];

            $hasLiveVideo = (bool)($settings['has_live_video'] ?? false);
            if (!$hasLiveVideo) {
                $row['liveid'] = null;
            }

            if (isset($settings['use_live_video'])) {
                $row['use_live_video'] = $hasLiveVideo && (bool)$settings['use_live_video'];
            } elseif ($hasLiveVideo) {
                $row['use_live_video'] = true;
            } else {
                $row['use_live_video'] = false;
            }
        }
        unset($row);

        return $rows;
    }

    // -------------------------------------------------------------------------
    // Path resolution
    // -------------------------------------------------------------------------

    private function resolveFilePaths(array $media, Folder $userFolder, string $userId, ?callable $onDebug = null): array {
        $items = [];
        $fileIds = array_map(static fn(array $row): int => (int)$row['file_id'], $media);
        $faceMap = $this->memoriesRepository->loadFaceDetections($fileIds, $userId);
        $subtleRunMotion = null;
        $subtleRunRemaining = 0;
        $lastSubtleRunMotion = null;
        $outputOrientation = $this->config->getUserValue(
            $userId,
            Application::APP_ID,
            'output_orientation',
            'landscape_16_9',
        );
        $targetAspect = match ($outputOrientation) {
            'portrait_9_16' => 9.0 / 16.0,
            'square_1_1' => 1.0,
            default => $this->targetAspect(),
        };

        foreach ($media as $row) {
            try {
                $fileId = (int)$row['file_id'];
                $useLive = !empty($row['use_live_video']) && !empty($row['liveid']);

                // If live video requested, try to find the .mov sibling via name-swap
                if ($useLive) {
                    $movFileId = $this->memoriesRepository->findLiveVideoFileId($fileId);
                    if ($movFileId !== null) {
                        $fileId = $movFileId;
                    } else {
                        $this->logger->info('Reel: .mov not found for live photo {id}, using still', ['id' => $row['file_id']]);
                        $useLive = false;
                    }
                }

                $files = $userFolder->getById($fileId);
                if (empty($files)) {
                    $this->logger->warning('Reel: could not find file {id}', ['id' => $fileId]);
                    continue;
                }

                $file      = $files[0];
                $localPath = $this->getLocalPath($file);

                if (!file_exists($localPath)) {
                    $this->logger->warning('Reel: file does not exist at {path}', ['path' => $localPath]);
                    continue;
                }

                $isVideo  = $useLive || (bool)$row['isvideo'];
                $interestingFocus = $isVideo
                    ? null
                    : $this->detectInterestingFocus($localPath);

                $dims = $isVideo
                    ? ['w' => (int)($row['w'] ?? 0), 'h' => (int)($row['h'] ?? 0)]
                    : $this->resolveImageDimensions(
                        $localPath,
                        (int)($row['w'] ?? 0),
                        (int)($row['h'] ?? 0),
                    );

                if ($isVideo) {
                    $motion = [];
                    // Video/live clips are "breakers" that reset subtle run grouping.
                    $subtleRunMotion = null;
                    $subtleRunRemaining = 0;
                } else {
                    if ($subtleRunMotion === null || $subtleRunRemaining <= 0) {
                        [$subtleRunMotion, $subtleRunRemaining] = $this->pickNextSubtleRun($lastSubtleRunMotion, (int)$row['file_id']);
                        $lastSubtleRunMotion = $subtleRunMotion;
                    }

                    $motion = $this->buildPhotoMotionSubtle(
                        (int)$row['file_id'],
                        $faceMap[(int)$row['file_id']] ?? [],
                        (int)$dims['w'],
                        (int)$dims['h'],
                        $interestingFocus,
                        $subtleRunMotion,
                    );
                    $motion['style'] = 'apple_subtle';
                    $motion['run_motion'] = $subtleRunMotion;
                    $motion['run_remaining'] = $subtleRunRemaining;
                    $dimW = (int)$dims['w'];
                    $dimH = (int)$dims['h'];
                    $motion['image_aspect'] = ($dimH > 0) ? ($dimW / $dimH) : $this->targetAspect();
                    $subtleRunRemaining--;
                }

                $duration = $isVideo
                    ? $this->resolveVideoDuration($localPath, $row, $useLive)
                    : (float)$motion['duration'];

                $videoStartAt = 0.0;
                if ($isVideo) {
                    [$videoStartAt, $duration] = $this->resolveVideoWindow($row, $duration, $useLive);
                }

                if ($onDebug) {
                    $sourceW = (int)$dims['w'];
                    $sourceH = (int)$dims['h'];
                    $sourceAspect = $sourceH > 0 ? ($sourceW / $sourceH) : 0.0;
                    $msg = sprintf(
                        '  Motion debug: file_id=%d src=%dx%d aspect=%.4f',
                        (int)$row['file_id'],
                        $sourceW,
                        $sourceH,
                        $sourceAspect,
                    );

                    if ($isVideo) {
                        $msg .= sprintf(' duration=%.2fs start=%.2fs live=%s', $duration, $videoStartAt, $useLive ? 'yes' : 'no');
                    } else {
                        $msg .= sprintf(' fy=%.4f duration=%.2fs', (float)($motion['fy'] ?? 0.5), (float)$duration); // this needs fixing - to contain info about the actual motion (zoom/pan, if any).
                    }

                    $msg .= ' path=' . basename($localPath);
                    $onDebug($msg);
                }

                $items[] = [
                    'file_id'  => (int)$row['file_id'],
                    'path'     => $localPath,
                    'is_video' => $isVideo,
                    'duration' => $duration,
                    'start_at' => $videoStartAt,
                    'w' => (int)$dims['w'],
                    'h' => (int)$dims['h'],
                    'liveid'   => $row['liveid'],
                    'motion'   => $motion,
                ];
            } catch (\Throwable $e) {
                $this->logger->warning('Reel: error resolving file {id}: {msg}', [
                    'id'  => $row['file_id'],
                    'msg' => $e->getMessage(),
                ]);
            }
        }

        return $items;
    }

    private function pickNextSubtleRun(?string $lastMotion, int $fileId): array {
        $motions = ['zoom_in', 'zoom_out'];
        $idx = abs((int)crc32($fileId . ':motion')) % count($motions);
        $motion = $motions[$idx];
        if ($lastMotion !== null && $motion === $lastMotion) {
            $motion = $motions[($idx + 1) % count($motions)];
        }

        $runLength = 2 + (abs((int)crc32($fileId . ':run')) % 3); // 2..4

        return [$motion, $runLength];
    }

    private function resolveVideoDuration(string $localPath, array $row, bool $isLive): float {
        $metadataDuration = (float)($row['video_duration'] ?? 0.0);
        $probedDuration = $this->probeVideoDurationSeconds($localPath);

        // For live photos, prefer real MOV metadata duration.
        // If probing fails, fall back to DB metadata and then a conservative default.
        if ($isLive) {
            if ($probedDuration !== null && $probedDuration > 0.0) {
                return $this->clamp($probedDuration, 0.6, self::MAX_CLIP_DURATION);
            }

            if ($metadataDuration > 0.0) {
                return $this->clamp($metadataDuration, 0.6, self::MAX_CLIP_DURATION);
            }

            return 2.8;
        }

        // Regular videos keep existing behavior but use probing as a fallback.
        $baseDuration = $metadataDuration > 0.0
            ? $metadataDuration
            : ($probedDuration ?? 0.0);

        if ($baseDuration <= 0.0) {
            return self::MAX_CLIP_DURATION;
        }

        return min($baseDuration, self::MAX_CLIP_DURATION);
    }

    private function resolveVideoWindow(array $row, float $baseDuration, bool $isLive): array {
        $baseDuration = $this->clamp($baseDuration, 0.6, self::MAX_CLIP_DURATION);
        if ($isLive) {
            return [0.0, $baseDuration];
        }

        $settings = [];
        if (!empty($row['edit_settings'])) {
            $decoded = json_decode((string)$row['edit_settings'], true);
            if (is_array($decoded)) {
                $settings = $decoded;
            }
        }

        $sourceDuration = (float)($row['video_duration'] ?? 0.0);
        if ($sourceDuration <= 0.0) {
            $sourceDuration = $baseDuration;
        }

        $requestedStart = isset($settings['video_start']) && is_numeric($settings['video_start'])
            ? max(0.0, (float)$settings['video_start'])
            : null;
        $requestedLengthRaw = $settings['video_length'] ?? ($settings['video_duration'] ?? null);
        $requestedLength = is_numeric($requestedLengthRaw)
            ? max(0.6, (float)$requestedLengthRaw)
            : null;

        $defaultLength = min(self::MAX_CLIP_DURATION, $sourceDuration);
        $length = $requestedLength !== null ? min($requestedLength, self::MAX_CLIP_DURATION) : $defaultLength;
        $length = min($length, max(0.6, $sourceDuration));

        if ($requestedStart !== null) {
            $start = $requestedStart;
        } elseif ($sourceDuration > ($length + 0.05)) {
            // For long videos, default to a centered segment instead of always the start.
            $start = max(0.0, ($sourceDuration - $length) / 2.0);
        } else {
            $start = 0.0;
        }

        $maxStart = max(0.0, $sourceDuration - $length);
        $start = min($start, $maxStart);

        return [$start, $length];
    }

    private function probeVideoDurationSeconds(string $localPath): ?float {
        $cmd = [
            'ffprobe',
            '-v', 'error',
            '-show_entries', 'format=duration',
            '-of', 'default=noprint_wrappers=1:nokey=1',
            $localPath,
        ];

        $process = proc_open(
            $cmd,
            [
                0 => ['pipe', 'r'],
                1 => ['pipe', 'w'],
                2 => ['pipe', 'w'],
            ],
            $pipes
        );

        if (!is_resource($process)) {
            return null;
        }

        fclose($pipes[0]);
        $stdout = stream_get_contents($pipes[1]);
        $stderr = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $exitCode = proc_close($process);

        if ($exitCode !== 0 || $stdout === false) {
            if (!empty($stderr)) {
                $this->logger->debug('Reel: ffprobe duration failed: {err}', ['err' => trim($stderr)]);
            }
            return null;
        }

        $duration = (float)trim($stdout);
        return $duration > 0.0 ? $duration : null;
    }

    private function buildPhotoMotionSubtle(
        int $fileId,
        array $faces,
        int $imageW,
        int $imageH,
        ?array $interestingFocus,
        string $runMotion,
    ): array {
        $seed = crc32((string)$fileId);
        $jx = (($seed & 0xffff) / 0xffff) - 0.5;
        $jy = ((($seed >> 16) & 0xffff) / 0xffff) - 0.5;
        $maxNoBlurZoom = $this->maxNoBlurZoom($imageW, $imageH);

        $baseFx = 0.5 + ($jx * 0.04);
        $baseFy = 0.5 + ($jy * 0.03);

        if (count($faces) > 0) {
            $sumX = 0.0;
            $sumY = 0.0;
            foreach ($faces as $face) {
                $mapped = $this->mapFocusToCoverFrame((float)$face['fx'], (float)$face['fy'], $imageW, $imageH);
                $sumX += (float)$mapped['fx'];
                $sumY += (float)$mapped['fy'];
            }

            $baseFx = $sumX / count($faces);
            $baseFy = ($sumY / count($faces)) - 0.02;
        } elseif ($interestingFocus !== null) {
            $mapped = $this->mapFocusToCoverFrame((float)$interestingFocus['fx'], (float)$interestingFocus['fy'], $imageW, $imageH);
            $baseFx = (0.65 * (float)$mapped['fx']) + (0.35 * $baseFx);
            $baseFy = (0.65 * (float)$mapped['fy']) + (0.35 * $baseFy);
        }

        $fx = $this->clamp($baseFx, 0.20, 0.80);
        $fy = $this->clamp($baseFy, 0.18, 0.82);
        $subtleZoom = min($maxNoBlurZoom, 1.06);
        $subtlePanZoom = min($maxNoBlurZoom, 1.02);
        $panDelta = 0.06;

        if (!empty($faces)) {
            $primaryFace = $this->pickPrimaryFace($faces);
            $mappedFace = $this->mapFaceBoxToCoverFrame(
                (float)$primaryFace['w'],
                (float)$primaryFace['h'],
                $imageW,
                $imageH,
            );
            $faceSize = max((float)$mappedFace['w'], (float)$mappedFace['h'], 0.08);
            $faceTargetZoom = $this->clamp(0.42 / $faceSize, 1.02, 1.10);
            $subtleZoom = min($maxNoBlurZoom, max($subtleZoom, $faceTargetZoom));
        }

        if ($runMotion === 'zoom_out') {
            return [
                'fx' => $fx,
                'fy' => $fy,
                'zoom_start' => $subtleZoom,
                'zoom_end' => 1.0,
                'duration' => self::PHOTO_DURATION,
            ];
        }

        if ($runMotion === 'pan_left') {
            $fxStart = $this->clamp($fx + $panDelta, 0.24, 0.84);
            $fxEnd = $this->clamp($fx - $panDelta, 0.16, 0.76);

            return [
                'mode' => 'pan_x',
                'pan_engine' => 'crop_ease_subtle',
                'fx_start' => $fxStart,
                'fx_end' => $fxEnd,
                'fy' => $fy,
                'zoom_start' => 1.0,
                'zoom_end' => $subtlePanZoom,
                'duration' => self::PHOTO_DURATION,
            ];
        }

        if ($runMotion === 'pan_right') {
            $fxStart = $this->clamp($fx - $panDelta, 0.16, 0.76);
            $fxEnd = $this->clamp($fx + $panDelta, 0.24, 0.84);

            return [
                'mode' => 'pan_x',
                'pan_engine' => 'crop_ease_subtle',
                'fx_start' => $fxStart,
                'fx_end' => $fxEnd,
                'fy' => $fy,
                'zoom_start' => 1.0,
                'zoom_end' => $subtlePanZoom,
                'duration' => self::PHOTO_DURATION,
            ];
        }

        return [
            'fx' => $fx,
            'fy' => $fy,
            'zoom_start' => 1.0,
            'zoom_end' => $subtleZoom,
            'duration' => self::PHOTO_DURATION,
        ];
    }

    private function buildPhotoMotion(
        int $fileId,
        array $faces,
        int $imageW,
        int $imageH,
        ?array $interestingFocus,
        float $mismatchThreshold,
        float $sweepMargin,
        float $panoramaSweepMargin,
        float $faceZoomTargetFill,
        float $nonFaceZoomEnd,
    ): array {
        $seed = crc32((string)$fileId);
        $jx = (($seed & 0xffff) / 0xffff) - 0.5;
        $jy = ((($seed >> 16) & 0xffff) / 0xffff) - 0.5;
        $safeMin = 0.08;
        $safeMax = 0.92;
        $maxNoBlurZoom = $this->maxNoBlurZoom($imageW, $imageH);
        $targetAspect = $this->targetAspect();
        $aspect = ($imageW > 0 && $imageH > 0) ? ($imageW / $imageH) : $targetAspect;
        $ratioToTarget = max($aspect / $targetAspect, $targetAspect / $aspect);
        $isMismatch = $ratioToTarget >= $mismatchThreshold;
        $isPanoramaWide = $aspect > ($targetAspect * 1.9);
        $isPanoramaTall = $aspect < ($targetAspect / 1.9);

        if (count($faces) === 1) {
            $face = $faces[0];
            $mapped = $this->mapFocusToCoverFrame((float)$face['fx'], (float)$face['fy'], $imageW, $imageH);
            $fx = $this->clamp($mapped['fx'], 0.16, 0.84);
            $fy = $this->clamp($mapped['fy'] - 0.03, 0.14, 0.86);
            $mappedFace = $this->mapFaceBoxToCoverFrame((float)$face['w'], (float)$face['h'], $imageW, $imageH);
            $faceSize = max((float)$mappedFace['w'], (float)$mappedFace['h'], 0.08);

            // Start at full-frame and end at target where the face fills configured share of viewport.
            $targetZoom = max(1.0, $faceZoomTargetFill / $faceSize);
            $zoomEnd = $this->clamp(min($targetZoom, $maxNoBlurZoom), 1.0, $maxNoBlurZoom);

            return [
                'fx' => $this->clamp($fx, $safeMin, $safeMax),
                'fy' => $this->clamp($fy, $safeMin, $safeMax),
                'zoom_start' => 1.0,
                'zoom_end' => $zoomEnd,
                'duration' => self::PHOTO_DURATION,
            ];
        }

        if (count($faces) > 1) {
            // Group framing: center on the face group and zoom to configured occupancy (capped).
            $minX = 1.0;
            $minY = 1.0;
            $maxX = 0.0;
            $maxY = 0.0;
            foreach ($faces as $face) {
                $mapped = $this->mapFocusToCoverFrame((float)$face['fx'], (float)$face['fy'], $imageW, $imageH);
                $fx = (float)$mapped['fx'];
                $fy = (float)$mapped['fy'];
                $mappedFace = $this->mapFaceBoxToCoverFrame((float)$face['w'], (float)$face['h'], $imageW, $imageH);
                $fw = (float)$mappedFace['w'];
                $fh = (float)$mappedFace['h'];
                $minX = min($minX, $fx - ($fw / 2.0));
                $maxX = max($maxX, $fx + ($fw / 2.0));
                $minY = min($minY, $fy - ($fh / 2.0));
                $maxY = max($maxY, $fy + ($fh / 2.0));
            }
            $groupW = max(0.08, $maxX - $minX);
            $groupH = max(0.08, $maxY - $minY);
            $groupSize = max($groupW, $groupH);
            $targetZoom = max(1.0, $faceZoomTargetFill / $groupSize);
            $zoomEnd = $this->clamp(min($targetZoom, $maxNoBlurZoom), 1.0, $maxNoBlurZoom);
            $groupFx = $this->clamp(($minX + $maxX) / 2.0, $safeMin, $safeMax);
            $groupFy = $this->clamp((($minY + $maxY) / 2.0) - 0.02, $safeMin, $safeMax);

            $extra = 0.0;
            for ($k = 2; $k <= count($faces); $k++) {
                $extra += (0.55 / ($k - 1));
            }

            return [
                'fx' => $groupFx,
                'fy' => $groupFy,
                'zoom_start' => 1.0,
                'zoom_end' => $zoomEnd,
                'duration' => min(5.0, self::PHOTO_DURATION + min(1.8, $extra)),
            ];
        }

        if ($isMismatch) {
            $mappedFocus = $interestingFocus !== null
                ? $this->mapFocusToCoverFrame((float)$interestingFocus['fx'], (float)$interestingFocus['fy'], $imageW, $imageH)
                : ['fx' => 0.5 + ($jx * 0.04), 'fy' => 0.5 + ($jy * 0.04)];

            $horizontalSweep = $aspect > $targetAspect;
            $edgeStart = ($isPanoramaWide || $isPanoramaTall)
                ? $panoramaSweepMargin
                : $sweepMargin;
            $edgeEnd = 1.0 - $edgeStart;
            $dirForward = ((($seed >> 3) & 1) === 0);
            $start = $dirForward ? $edgeStart : $edgeEnd;
            $end = $dirForward ? $edgeEnd : $edgeStart;
            $configuredSweepZoom = $this->clamp($nonFaceZoomEnd * 0.70, 1.03, 1.26);
            $configuredPanoramaSweepZoom = $this->clamp($nonFaceZoomEnd * 0.58, 1.01, 1.12);
            $sweepZoom = ($isPanoramaWide || $isPanoramaTall)
                ? min($maxNoBlurZoom, $configuredPanoramaSweepZoom)
                : min($maxNoBlurZoom, $configuredSweepZoom);

            if ($horizontalSweep) {
                return [
                    'mode' => 'pan_x',
                    'pan_engine' => 'crop_ease',
                    'fx_start' => $start,
                    'fx_end' => $end,
                    'fy' => $this->clamp((float)$mappedFocus['fy'], 0.14, 0.86),
                    'zoom_start' => 1.0,
                    'zoom_end' => $sweepZoom,
                    'duration' => self::PHOTO_DURATION,
                ];
            }

            return [
                'mode' => 'pan_y',
                'pan_engine' => 'crop_ease',
                'fx' => $this->clamp((float)$mappedFocus['fx'], 0.14, 0.86),
                'fy_start' => $start,
                'fy_end' => $end,
                'zoom_start' => 1.0,
                'zoom_end' => $sweepZoom,
                'duration' => self::PHOTO_DURATION,
            ];
        }

        // No faces: zoom on an "interesting" detected point with deterministic per-image jitter.
        // If saliency is weak or biased, this still avoids always picking the same viewport region.
        if ($interestingFocus !== null) {
            $mappedFocus = $this->mapFocusToCoverFrame((float)$interestingFocus['fx'], (float)$interestingFocus['fy'], $imageW, $imageH);
            // Blend saliency with seeded per-image variation so no-face shots don't converge.
            $baseFx = ($mappedFocus['fx'] * 0.72) + ((0.5 + ($jx * 0.40)) * 0.28);
            $baseFy = ($mappedFocus['fy'] * 0.72) + ((0.5 + ($jy * 0.38)) * 0.28);
        } else {
            $baseFx = 0.5 + ($jx * 0.36);
            $baseFy = 0.5 + ($jy * 0.34);
        }

        $fx = $this->clamp((float)$baseFx + ($jx * 0.16), $safeMin, $safeMax);
        $fy = $this->clamp((float)$baseFy + ($jy * 0.14), $safeMin, $safeMax);
        return [
            'fx' => $this->clamp((float)$fx, $safeMin, $safeMax),
            'fy' => $this->clamp((float)$fy, $safeMin, $safeMax),
            'zoom_start' => 1.0,
            'zoom_end' => min($maxNoBlurZoom, $nonFaceZoomEnd),
            'duration' => self::PHOTO_DURATION,
        ];
    }

    private function resolveImageDimensions(string $localPath, int $fallbackW, int $fallbackH): array {
        $w = $fallbackW;
        $h = $fallbackH;

        // Prefer Imagick metadata because it can represent orientation reliably for more formats.
        if (class_exists(\Imagick::class)) {
            try {
                $img = new \Imagick();
                $img->readImage($localPath . '[0]');
                $iw = (int)$img->getImageWidth();
                $ih = (int)$img->getImageHeight();
                if ($iw > 0 && $ih > 0) {
                    $w = $iw;
                    $h = $ih;
                }

                $orientation = (int)$img->getImageOrientation();
                if (in_array($orientation, [
                    \Imagick::ORIENTATION_LEFTTOP,
                    \Imagick::ORIENTATION_RIGHTTOP,
                    \Imagick::ORIENTATION_RIGHTBOTTOM,
                    \Imagick::ORIENTATION_LEFTBOTTOM,
                ], true)) {
                    $tmp = $w;
                    $w = $h;
                    $h = $tmp;
                }

                $img->destroy();
            } catch (\Throwable $e) {
                // Fall through to other probes/fallbacks.
            }
        }

        if ($w <= 0 || $h <= 0) {
            $raw = @getimagesize($localPath);
            if (is_array($raw) && !empty($raw[0]) && !empty($raw[1])) {
                $w = (int)$raw[0];
                $h = (int)$raw[1];
            }
        }

        if ($w <= 0 || $h <= 0) {
            $w = max(1, $fallbackW);
            $h = max(1, $fallbackH);
        }

        return ['w' => $w, 'h' => $h];
    }

    private function getOutputDimensions(string $userId): array {
        $orientation = $this->config->getUserValue(
            $userId,
            Application::APP_ID,
            'output_orientation',
            'landscape_16_9',
        );

        return match ($orientation) {
            'portrait_9_16' => [1080, 1920],
            'square_1_1' => [1080, 1080],
            default => [self::WIDTH, self::HEIGHT],
        };
    }

    private function outputWidth(): int {
        return $this->outputWidth;
    }

    private function outputHeight(): int {
        return $this->outputHeight;
    }

    private function targetAspect(): float {
        return $this->outputWidth() / max(1, $this->outputHeight());
    }

    /**
     * Lightweight saliency approximation: pick the highest-detail tile in a dense grid.
     */
    private function detectInterestingFocus(string $localPath): ?array {
        if (!class_exists(\Imagick::class)) {
            return null;
        }

        try {
            $img = new \Imagick();
            $img->readImage($localPath . '[0]');
            $img->thumbnailImage(384, 384, true, true);
            $img->setImageColorspace(\Imagick::COLORSPACE_GRAY);
            $img->edgeImage(1);

            $w = $img->getImageWidth();
            $h = $img->getImageHeight();
            if ($w < 3 || $h < 3) {
                $img->destroy();
                return null;
            }

            $bestScore = -1.0;
            $bestFx = 0.5;
            $bestFy = 0.5;
            $aspect = $h > 0 ? ($w / $h) : 1.0;
            $gridX = 4;
            $gridY = 4;
            if ($aspect > 2.5) {
                $gridX = 6;
                $gridY = 3;
            } elseif ($aspect < 0.4) {
                $gridX = 3;
                $gridY = 6;
            }

            for ($gy = 0; $gy < $gridY; $gy++) {
                for ($gx = 0; $gx < $gridX; $gx++) {
                    $x = (int)floor(($gx * $w) / $gridX);
                    $y = (int)floor(($gy * $h) / $gridY);
                    $x2 = (int)floor((($gx + 1) * $w) / $gridX);
                    $y2 = (int)floor((($gy + 1) * $h) / $gridY);
                    $tw = max(1, $x2 - $x);
                    $th = max(1, $y2 - $y);

                    $tile = clone $img;
                    $tile->cropImage($tw, $th, $x, $y);
                    $stats = $tile->getImageChannelStatistics();
                    $tile->destroy();

                    $stddev = 0.0;
                    foreach ($stats as $channelStats) {
                        if (!is_array($channelStats) || !isset($channelStats['standardDeviation'])) {
                            continue;
                        }
                        $stddev = max($stddev, (float)$channelStats['standardDeviation']);
                    }

                    // Slight center bias to avoid extreme corners unless they are clearly more detailed.
                    $cx = (($x + ($tw / 2.0)) / $w);
                    $cy = (($y + ($th / 2.0)) / $h);
                    $centerBias = 1.0 - (0.15 * sqrt(($cx - 0.5) ** 2 + ($cy - 0.5) ** 2));
                    $score = $stddev * $centerBias;
                    if ($score > $bestScore) {
                        $bestScore = $score;
                        $bestFx = $cx;
                        $bestFy = $cy;
                    }
                }
            }

            $img->destroy();
            return ['fx' => $bestFx, 'fy' => $bestFy];
        } catch (\Throwable $e) {
            return null;
        }
    }

    private function maxNoBlurZoom(int $imageW, int $imageH): float {
        if ($imageW <= 0 || $imageH <= 0) {
            return 1.35;
        }

        $limit = min($imageW / $this->outputWidth(), $imageH / $this->outputHeight());
        return max(1.0, min(2.2, $limit));
    }

    /**
     * Convert a focus point from source-normalized coordinates into the
     * normalized coordinates after cover-scale + center-crop to output frame.
     */
    private function mapFocusToCoverFrame(float $fx, float $fy, int $imageW, int $imageH): array {
        $fx = $this->clamp($fx, 0.0, 1.0);
        $fy = $this->clamp($fy, 0.0, 1.0);

        if ($imageW <= 0 || $imageH <= 0) {
            return ['fx' => $fx, 'fy' => $fy];
        }

        $outW = $this->outputWidth();
        $outH = $this->outputHeight();
        $scale = max($outW / $imageW, $outH / $imageH);
        $scaledW = $imageW * $scale;
        $scaledH = $imageH * $scale;
        $cropX = max(0.0, ($scaledW - $outW) / 2.0);
        $cropY = max(0.0, ($scaledH - $outH) / 2.0);

        $px = ($fx * $scaledW) - $cropX;
        $py = ($fy * $scaledH) - $cropY;

        return [
            'fx' => $this->clamp($px / $outW, 0.0, 1.0),
            'fy' => $this->clamp($py / $outH, 0.0, 1.0),
        ];
    }

    private function mapFaceBoxToCoverFrame(float $faceW, float $faceH, int $imageW, int $imageH): array {
        $faceW = $this->clamp($faceW, 0.0, 1.0);
        $faceH = $this->clamp($faceH, 0.0, 1.0);

        if ($imageW <= 0 || $imageH <= 0) {
            return ['w' => $faceW, 'h' => $faceH];
        }

        $outW = $this->outputWidth();
        $outH = $this->outputHeight();
        $scale = max($outW / $imageW, $outH / $imageH);
        $scaledW = $imageW * $scale;
        $scaledH = $imageH * $scale;

        return [
            'w' => $this->clamp(($faceW * $scaledW) / $outW, 0.0, 1.0),
            'h' => $this->clamp(($faceH * $scaledH) / $outH, 0.0, 1.0),
        ];
    }

    private function pickPrimaryFace(array $faces): array {
        $bestFace = $faces[0] ?? ['w' => 0.0, 'h' => 0.0, 'fx' => 0.5, 'fy' => 0.5];
        $bestScore = -1.0;

        foreach ($faces as $face) {
            $w = max(0.0, (float)($face['w'] ?? 0.0));
            $h = max(0.0, (float)($face['h'] ?? 0.0));
            $score = $w * $h;
            if ($score > $bestScore) {
                $bestScore = $score;
                $bestFace = $face;
            }
        }

        return $bestFace;
    }

    private function isStrongAspectMismatch(float $sourceAspect, float $targetAspect): bool {
        if ($sourceAspect <= 0.0 || $targetAspect <= 0.0) {
            return false;
        }

        $ratio = max($sourceAspect / $targetAspect, $targetAspect / $sourceAspect);
        return $ratio >= 1.65;
    }

    private function easeInOutCubicExpr(string $tExpr): string {
        return "if(lt({$tExpr},0.5),4*pow({$tExpr},3),1-pow(-2*{$tExpr}+2,3)/2)";
    }

    private function clamp(float $value, float $min, float $max): float {
        return max($min, min($max, $value));
    }

    private function getLocalPath(\OCP\Files\Node $node): string {
        $storage = $node->getStorage();

        if (!$storage->isLocal()) {
            throw new \RuntimeException('Reel only supports local storage for rendering');
        }

        $localFile = $storage->getLocalFile($node->getInternalPath());
        if ($localFile === null) {
            throw new \RuntimeException('Could not get local path for ' . $node->getPath());
        }

        return $localFile;
    }

    // -------------------------------------------------------------------------
    // Output folder
    // -------------------------------------------------------------------------

    private function ensureOutputFolder(Folder $userFolder): Folder {
        if ($userFolder->nodeExists(self::OUTPUT_FOLDER)) {
            $node = $userFolder->get(self::OUTPUT_FOLDER);
            if (!$node instanceof Folder) {
                throw new \RuntimeException(self::OUTPUT_FOLDER . ' exists but is not a folder');
            }
            return $node;
        }

        return $userFolder->newFolder(self::OUTPUT_FOLDER);
    }

    private function persistOutputFile(Folder $outputFolder, string $outputName, string $localOutputPath): File {
        $node = $outputFolder->nodeExists($outputName)
            ? $outputFolder->get($outputName)
            : $outputFolder->newFile($outputName);

        if (!$node instanceof File) {
            throw new \RuntimeException($outputName . ' exists but is not a file');
        }

        $in = fopen($localOutputPath, 'rb');
        if ($in === false) {
            throw new \RuntimeException('Failed to open rendered file for import');
        }

        $out = $node->fopen('w');
        if (!is_resource($out)) {
            fclose($in);
            throw new \RuntimeException('Failed to open destination file in Nextcloud storage');
        }

        stream_copy_to_stream($in, $out);
        fclose($in);
        fclose($out);

        return $node;
    }

    private function buildOutputFilename(array $event): string {
        $slug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $event['title'] ?? 'reel'));
        $slug = trim($slug, '-');
        if (strlen($slug) > 80) {
            $slug = rtrim(substr($slug, 0, 80), '-');
        }
        return 'reel-' . $slug . '-' . $event['id'] . '.mp4';
    }

    private function getMusicPath(?string $theme, string $userId): ?string {
        if (is_string($theme) && str_starts_with($theme, 'custom:')) {
            $customPath = substr($theme, strlen('custom:'));
            if ($customPath !== false && $customPath !== '') {
                return $this->musicService->resolveCustomMusicFilePath($userId, $customPath);
            }
        }

        $genre = $this->normalizeMusicGenre($theme);
        return $this->musicService->getRandomBundledMusicFile($genre);
    }

    private function normalizeMusicGenre(?string $theme): string {
        return match($theme) {
            'acoustic_folk', 'indie_pop', 'cinematic_orchestral' => $theme,
            // Backwards compatibility for old themes.
            'summer' => 'acoustic_folk',
            'minimal' => 'cinematic_orchestral',
            default => 'indie_pop',
        };
    }

    // -------------------------------------------------------------------------
    // FFmpeg execution
    // -------------------------------------------------------------------------

    private function runFfmpeg(array $cmd): void {
        $process = proc_open(
            $cmd,
            [
                0 => ['pipe', 'r'],
                1 => ['pipe', 'w'],
                2 => ['pipe', 'w'],
            ],
            $pipes
        );

        if (!is_resource($process)) {
            throw new \RuntimeException('Failed to start FFmpeg process');
        }

        fclose($pipes[0]);
        stream_set_blocking($pipes[1], false);
        stream_set_blocking($pipes[2], false);

        $startedAt = time();
        $stderr = '';

        while (true) {
            $status = proc_get_status($process);

            $errChunk = stream_get_contents($pipes[2]);
            if ($errChunk !== false && $errChunk !== '') {
                if (strlen($stderr) < self::FFMPEG_STDERR_MAX_BYTES) {
                    $stderr .= substr($errChunk, 0, self::FFMPEG_STDERR_MAX_BYTES - strlen($stderr));
                }
            }

            if (!$status['running']) {
                break;
            }

            if ((time() - $startedAt) > self::FFMPEG_TIMEOUT_SECONDS) {
                proc_terminate($process);
                usleep(200000);
                $status = proc_get_status($process);
                if ($status['running']) {
                    proc_terminate($process, 9);
                }

                fclose($pipes[1]);
                fclose($pipes[2]);
                proc_close($process);

                throw new \RuntimeException('FFmpeg timed out and was terminated');
            }

            usleep(100000);
        }

        // Drain any remaining stderr output once the process exits.
        $errChunk = stream_get_contents($pipes[2]);
        if ($errChunk !== false && $errChunk !== '') {
            if (strlen($stderr) < self::FFMPEG_STDERR_MAX_BYTES) {
                $stderr .= substr($errChunk, 0, self::FFMPEG_STDERR_MAX_BYTES - strlen($stderr));
            }
        }

        fclose($pipes[1]);
        fclose($pipes[2]);
        $exitCode = (int)($status['exitcode'] ?? -1);
        $closeCode = proc_close($process);
        if ($exitCode === -1) {
            $exitCode = $closeCode;
        }

        if ($exitCode !== 0) {
            $this->logger->error('Reel: FFmpeg failed (exit {code}): {stderr}', [
                'code'   => $exitCode,
                'stderr' => $stderr,
            ]);
            throw new \RuntimeException("FFmpeg exited with code {$exitCode}: " . substr($stderr, -500));
        }
    }

    // -------------------------------------------------------------------------
    // Cleanup + DB
    // -------------------------------------------------------------------------

    private function cleanupTempDir(string $tempDir): void {
        if (!is_dir($tempDir)) return;
        foreach (glob($tempDir . '/*') ?: [] as $file) {
            @unlink($file);
        }
        @rmdir($tempDir);
    }

    private function updateEventVideoFileId(int $eventId, string $userId, int $fileId): void {
        $qb = $this->db->getQueryBuilder();
        $qb->update('reel_events')
            ->set('video_file_id', $qb->createNamedParameter($fileId, IQueryBuilder::PARAM_INT))
            ->set('updated_at',    $qb->createNamedParameter(time(),   IQueryBuilder::PARAM_INT))
            ->where($qb->expr()->eq('id', $qb->createNamedParameter($eventId, IQueryBuilder::PARAM_INT)))
            ->andWhere($qb->expr()->eq('user_id', $qb->createNamedParameter($userId)))
            ->executeStatement();
    }
}
